### ISSUE TITLE
todo saturday

### ISSUE THREAD

**Issue by edunham** [edunham/engr421#2]
- [ ] fake camera that reads image from file during get_frame and uses preset tmat and gutted calibrate
- [x] modify threshholds if >2 pucks allegedly detected, until exactly 2 are in sight? slower but more reliable... perhaps only if selection strategy is indecisive?
- [ ] proper inheritance for fakearduino, or a clever thing that aliases all functions to a thing that just prints its arguments
- [ ] sleep
